module.exports = {
    arr: require('./lib/Array'),
    constant: require('./lib/Constant'),
    copy: require('./lib/Copy'),
    ...require('./lib/Debounce'),
    ...require('./lib/Fibonacci'),
    log: require('./lib/Log'),
    math: require('./lib/Math'),
    obj: require('./lib/Object'),
    regex: require('./lib/Regex'),
    // ...require('./lib/Storage'),
    ...require('./lib/Throttle'),
    time: require('./lib/Time'),
    tree: require('./lib/Tree'),
    type: require('./lib/Type'),
    url: require('./lib/Url'),
    utils: require('./lib/utils'),
}
